--- 
algolia: 
  application_id: ~
  index_name: ~
  powered_by: ~
  search_only_api_key: ~
author: ~
baseurl: /jekyll-theme-basically-basic
description: "my personal pages"
email: ~
github_username: williamz0112
lang: zh_CN
logo: /assets/images/logo.png
markdown: kramdown
name: "william zheng"
picture: ~
search: ~
search_full_content: false
search_provider: ~
title: "willliam task"
twitter: ~
twitter_username: ~
url: "https://gitee.com/william159"
-theme-basically-basic
plugins: # previsously gems
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Exclude from processing.
exclude:
  - .asset-cache
  - .bundle
  - .codeclimate.yml
  - .editorconfig
  - .gitattributes
  - .jekyll-assets-cache
  - .sass-cache
  - .scss-lint.yml
  - CHANGELOG
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules
  - Rakefile
  - README
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - /docs # ignore Basically Basic sample site
  - /example # ignore Basically Basic dev site

# Front Matter Defaults
defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      read_time: true
